### PR TITLE
Enhancement/security

### PR DESCRIPTION
**Pull request by ins0**
This PR

- [x] adds a method to obfuscate risky config key values like
 - ``password, username, pwd, dsn, ... ``

As i see many developers don't know or forget that enable the dev toolbar online, expose their complete config credentials. 

I know this is a development module but it think it is fair to force developers to look at such config values directly in the files.

Before:

```php
Array
(
    [username] => superSecretUsername
    [password] => superSecretPassword
    [nested] => Array
        (
            [dsn] => superSecretConnectionString
        )
)
```

After:

```php
Array
(
    [username] => ******
    [password] => ******
    [nested] => Array
        (
            [dsn] => ******
        )
)
```

ping @Ocramius

### CODE REVIEW

**Comment by snapshotpl** [comment]
:-1: It can make unexpected behavior if I want to check my config in devtoolbar

**Comment by ins0** [comment]
thanks for your feedback @snapshotpl. i know this approach is not failsafe, maybe a better option if this only would take place for config keys which are well known like for ``Zend\Db`` and ``Doctrine``?

**Comment by Ocramius** [comment]
Agree with @snapshotpl here: the toolbar is a debugging tool, and if you copy any information from anywhere (stack trace, exception message, code snippet, etc) then it is your responsibility to strip out information from it.

In addition to that, ZDT is not meant to be used in production environments anyway, as it doesn't expose flags to enable/disable it depending on who is accessing the environment (and we won't go there anyway, as it is a big security can of worms).

If we do strip information for the user, we're just making it harder to debug the main reason why you'd use this tool in first place: dumping runtime information for the developer.

I'd rather add a visual warning to the toolbar itself.

**Comment by ins0** [comment]
yeah you're right. thanks @snapshotpl @Ocramius for your feedback make sense to me now. I didn't thought about the option showing a simpe warning instead.

so something like

- check if devbar is running on a valid tld
- show message "Hey it looks like you're running the Developer Toolbar on a public accessible domain. Please keep in mind that this could lead to leak sensitive information to the public (e.g Database access credentials)

- give the possibility to disable the message in the config for teams that working on valid tld that are protected or localy

**Comment by Ocramius** [comment]
@ins0 the warning should probably be displayed also (generally) to avoid wild copy-pasting :)

**Comment by ins0** [comment]
@snapshotpl your opinion on this?

**Comment by snapshotpl** [comment]
Warning message is welcome. However I'm scare about developers community after you have found "~1200 websites" ;)

**Comment by ins0** [comment]
Ok 1200 is not very accurate as googles search results are calculated but the point is that this tool is widely used and it looks like they don't know that this leaks live/online access credentials.

not like a google search of ``filetype:txt username password`` or something like this and hope they are still working.

**Comment by snapshotpl** [comment]
My winner is https://www.google.pl/search?q="application.ini"+"index+of" from ZF1...

**Comment by weierophinney** [comment]
Based on the discussion here, I'm going to close this. @ins0 — if you (or others reading this) find the time, please open a PR that will implement the warning, and many thanks in advance!

**Pull request closed without merging**
