### PR TITLE
update zendframework logo in toolbar: "ZF2" -> "ZF"

### PR DESCRIPTION
**Pull request by samsonasik**
**Before** :
before-zf-toolbar

**After** :
new-zf-toolbar

### CODE REVIEW

**Comment by samsonasik** [comment]
@weierophinney this should be merge-able ;)

**Comment by RalfEggert** [comment]
Please merge! @weierophinney

**Comment by RalfEggert** [comment]
Again, please merge this. I always need to explain to beginners, why the ZF3 comes with a tool bar that shows a ZF2 logo. Must don't get it and ask why it is not changed... ;-)

**Comment by weierophinney** [comment]
Thanks, @samsonasik

**Pull request merged**
