### PR TITLE
Fix hover on toolbar item

### PR DESCRIPTION
**Pull request by snapshotpl**

### CODE REVIEW

**Comment by Ocramius** [comment]
@snapshotpl what does this fix exactly? Screen pre/post?

**Comment by snapshotpl** [comment]
It's the same issue like #164

**Comment by snapshotpl** [comment]
I have found that issue still exists in some case, class selector is duplicated

**Comment by Ocramius** [comment]
@snapshotpl thanks!

**Comment by snapshotpl** [comment]
@Ocramius You welcome! :-)

**Pull request merged**
